language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - python manage.py migrate
env:
  - DJANGO_SETTINGS_MODULE="mysite.settings"
script:
  - black --check blogging mysite polling
  - python manage.py test